/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedDaybookRouteImport } from './routes/_authenticated/daybook'
import { Route as AuthenticatedAdditionalIndexRouteImport } from './routes/_authenticated/additional.index'
import { Route as AuthenticatedAdditionalTemperatureRouteImport } from './routes/_authenticated/additional.temperature'
import { Route as AuthenticatedBookingIndexRouteImport } from './routes/_authenticated/booking.index'
import { Route as AuthenticatedBookingIdRouteImport } from './routes/_authenticated/booking.$id'
import { Route as AuthenticatedBookingEditHistoryRouteImport } from './routes/_authenticated/booking.edit-history'
import { Route as AuthenticatedDispatchPostStorageReportRouteImport } from './routes/_authenticated/dispatch-post-storage.report'
import { Route as AuthenticatedDispatchPreStorageIndexRouteImport } from './routes/_authenticated/dispatch-pre-storage.index'
import { Route as AuthenticatedDispatchPreStorageIdRouteImport } from './routes/_authenticated/dispatch-pre-storage.$id'
import { Route as AuthenticatedDispatchPreStorageReportRouteImport } from './routes/_authenticated/dispatch-pre-storage.report'
import { Route as AuthenticatedDispatchIndexRouteImport } from './routes/_authenticated/dispatch.index'
import { Route as AuthenticatedDispatchIdRouteImport } from './routes/_authenticated/dispatch.$id'
import { Route as AuthenticatedDispatchReportRouteImport } from './routes/_authenticated/dispatch.report'
import { Route as AuthenticatedGradingIndexRouteImport } from './routes/_authenticated/grading.index'
import { Route as AuthenticatedGradingIdRouteImport } from './routes/_authenticated/grading.$id'
import { Route as AuthenticatedGradingEditHistoryRouteImport } from './routes/_authenticated/grading.edit-history'
import { Route as AuthenticatedGradingReportRouteImport } from './routes/_authenticated/grading.report'
import { Route as AuthenticatedIncomingIndexRouteImport } from './routes/_authenticated/incoming.index'
import { Route as AuthenticatedIncomingIdRouteImport } from './routes/_authenticated/incoming.$id'
import { Route as AuthenticatedIncomingEditHistoryRouteImport } from './routes/_authenticated/incoming.edit-history'
import { Route as AuthenticatedIncomingReportRouteImport } from './routes/_authenticated/incoming.report'
import { Route as AuthenticatedOutgoingIndexRouteImport } from './routes/_authenticated/outgoing.index'
import { Route as AuthenticatedPeopleIndexRouteImport } from './routes/_authenticated/people.index'
import { Route as AuthenticatedPeopleIdRouteImport } from './routes/_authenticated/people.$id'
import { Route as AuthenticatedStorageIndexRouteImport } from './routes/_authenticated/storage.index'
import { Route as AuthenticatedStorageIdRouteImport } from './routes/_authenticated/storage.$id'
import { Route as AuthenticatedStorageEditHistoryRouteImport } from './routes/_authenticated/storage.edit-history'
import { Route as AuthenticatedStorageReportRouteImport } from './routes/_authenticated/storage.report'
import { Route as AuthenticatedTransferIndexRouteImport } from './routes/_authenticated/transfer.index'
import { Route as AuthenticatedTransferReportRouteImport } from './routes/_authenticated/transfer.report'
import { Route as AuthenticatedStorageChamberBreakdownChamberRouteImport } from './routes/_authenticated/storage.chamber-breakdown.$chamber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDaybookRoute = AuthenticatedDaybookRouteImport.update({
  id: '/daybook',
  path: '/daybook',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdditionalIndexRoute =
  AuthenticatedAdditionalIndexRouteImport.update({
    id: '/additional/',
    path: '/additional/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdditionalTemperatureRoute =
  AuthenticatedAdditionalTemperatureRouteImport.update({
    id: '/additional/temperature',
    path: '/additional/temperature',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookingIndexRoute =
  AuthenticatedBookingIndexRouteImport.update({
    id: '/booking/',
    path: '/booking/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookingIdRoute = AuthenticatedBookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookingEditHistoryRoute =
  AuthenticatedBookingEditHistoryRouteImport.update({
    id: '/booking/edit-history',
    path: '/booking/edit-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDispatchPostStorageReportRoute =
  AuthenticatedDispatchPostStorageReportRouteImport.update({
    id: '/dispatch-post-storage/report',
    path: '/dispatch-post-storage/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDispatchPreStorageIndexRoute =
  AuthenticatedDispatchPreStorageIndexRouteImport.update({
    id: '/dispatch-pre-storage/',
    path: '/dispatch-pre-storage/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDispatchPreStorageIdRoute =
  AuthenticatedDispatchPreStorageIdRouteImport.update({
    id: '/dispatch-pre-storage/$id',
    path: '/dispatch-pre-storage/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDispatchPreStorageReportRoute =
  AuthenticatedDispatchPreStorageReportRouteImport.update({
    id: '/dispatch-pre-storage/report',
    path: '/dispatch-pre-storage/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDispatchIndexRoute =
  AuthenticatedDispatchIndexRouteImport.update({
    id: '/dispatch/',
    path: '/dispatch/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDispatchIdRoute = AuthenticatedDispatchIdRouteImport.update({
  id: '/dispatch/$id',
  path: '/dispatch/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDispatchReportRoute =
  AuthenticatedDispatchReportRouteImport.update({
    id: '/dispatch/report',
    path: '/dispatch/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGradingIndexRoute =
  AuthenticatedGradingIndexRouteImport.update({
    id: '/grading/',
    path: '/grading/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGradingIdRoute = AuthenticatedGradingIdRouteImport.update({
  id: '/grading/$id',
  path: '/grading/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGradingEditHistoryRoute =
  AuthenticatedGradingEditHistoryRouteImport.update({
    id: '/grading/edit-history',
    path: '/grading/edit-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGradingReportRoute =
  AuthenticatedGradingReportRouteImport.update({
    id: '/grading/report',
    path: '/grading/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncomingIndexRoute =
  AuthenticatedIncomingIndexRouteImport.update({
    id: '/incoming/',
    path: '/incoming/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncomingIdRoute = AuthenticatedIncomingIdRouteImport.update({
  id: '/incoming/$id',
  path: '/incoming/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncomingEditHistoryRoute =
  AuthenticatedIncomingEditHistoryRouteImport.update({
    id: '/incoming/edit-history',
    path: '/incoming/edit-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncomingReportRoute =
  AuthenticatedIncomingReportRouteImport.update({
    id: '/incoming/report',
    path: '/incoming/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOutgoingIndexRoute =
  AuthenticatedOutgoingIndexRouteImport.update({
    id: '/outgoing/',
    path: '/outgoing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPeopleIndexRoute =
  AuthenticatedPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPeopleIdRoute = AuthenticatedPeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStorageIndexRoute =
  AuthenticatedStorageIndexRouteImport.update({
    id: '/storage/',
    path: '/storage/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStorageIdRoute = AuthenticatedStorageIdRouteImport.update({
  id: '/storage/$id',
  path: '/storage/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStorageEditHistoryRoute =
  AuthenticatedStorageEditHistoryRouteImport.update({
    id: '/storage/edit-history',
    path: '/storage/edit-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStorageReportRoute =
  AuthenticatedStorageReportRouteImport.update({
    id: '/storage/report',
    path: '/storage/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransferIndexRoute =
  AuthenticatedTransferIndexRouteImport.update({
    id: '/transfer/',
    path: '/transfer/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransferReportRoute =
  AuthenticatedTransferReportRouteImport.update({
    id: '/transfer/report',
    path: '/transfer/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStorageChamberBreakdownChamberRoute =
  AuthenticatedStorageChamberBreakdownChamberRouteImport.update({
    id: '/storage/chamber-breakdown/$chamber',
    path: '/storage/chamber-breakdown/$chamber',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/daybook': typeof AuthenticatedDaybookRoute
  '/additional/temperature': typeof AuthenticatedAdditionalTemperatureRoute
  '/booking/$id': typeof AuthenticatedBookingIdRoute
  '/booking/edit-history': typeof AuthenticatedBookingEditHistoryRoute
  '/dispatch-post-storage/report': typeof AuthenticatedDispatchPostStorageReportRoute
  '/dispatch-pre-storage/$id': typeof AuthenticatedDispatchPreStorageIdRoute
  '/dispatch-pre-storage/report': typeof AuthenticatedDispatchPreStorageReportRoute
  '/dispatch/$id': typeof AuthenticatedDispatchIdRoute
  '/dispatch/report': typeof AuthenticatedDispatchReportRoute
  '/grading/$id': typeof AuthenticatedGradingIdRoute
  '/grading/edit-history': typeof AuthenticatedGradingEditHistoryRoute
  '/grading/report': typeof AuthenticatedGradingReportRoute
  '/incoming/$id': typeof AuthenticatedIncomingIdRoute
  '/incoming/edit-history': typeof AuthenticatedIncomingEditHistoryRoute
  '/incoming/report': typeof AuthenticatedIncomingReportRoute
  '/people/$id': typeof AuthenticatedPeopleIdRoute
  '/storage/$id': typeof AuthenticatedStorageIdRoute
  '/storage/edit-history': typeof AuthenticatedStorageEditHistoryRoute
  '/storage/report': typeof AuthenticatedStorageReportRoute
  '/transfer/report': typeof AuthenticatedTransferReportRoute
  '/additional/': typeof AuthenticatedAdditionalIndexRoute
  '/booking/': typeof AuthenticatedBookingIndexRoute
  '/dispatch-pre-storage/': typeof AuthenticatedDispatchPreStorageIndexRoute
  '/dispatch/': typeof AuthenticatedDispatchIndexRoute
  '/grading/': typeof AuthenticatedGradingIndexRoute
  '/incoming/': typeof AuthenticatedIncomingIndexRoute
  '/outgoing/': typeof AuthenticatedOutgoingIndexRoute
  '/people/': typeof AuthenticatedPeopleIndexRoute
  '/storage/': typeof AuthenticatedStorageIndexRoute
  '/transfer/': typeof AuthenticatedTransferIndexRoute
  '/storage/chamber-breakdown/$chamber': typeof AuthenticatedStorageChamberBreakdownChamberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/daybook': typeof AuthenticatedDaybookRoute
  '/additional/temperature': typeof AuthenticatedAdditionalTemperatureRoute
  '/booking/$id': typeof AuthenticatedBookingIdRoute
  '/booking/edit-history': typeof AuthenticatedBookingEditHistoryRoute
  '/dispatch-post-storage/report': typeof AuthenticatedDispatchPostStorageReportRoute
  '/dispatch-pre-storage/$id': typeof AuthenticatedDispatchPreStorageIdRoute
  '/dispatch-pre-storage/report': typeof AuthenticatedDispatchPreStorageReportRoute
  '/dispatch/$id': typeof AuthenticatedDispatchIdRoute
  '/dispatch/report': typeof AuthenticatedDispatchReportRoute
  '/grading/$id': typeof AuthenticatedGradingIdRoute
  '/grading/edit-history': typeof AuthenticatedGradingEditHistoryRoute
  '/grading/report': typeof AuthenticatedGradingReportRoute
  '/incoming/$id': typeof AuthenticatedIncomingIdRoute
  '/incoming/edit-history': typeof AuthenticatedIncomingEditHistoryRoute
  '/incoming/report': typeof AuthenticatedIncomingReportRoute
  '/people/$id': typeof AuthenticatedPeopleIdRoute
  '/storage/$id': typeof AuthenticatedStorageIdRoute
  '/storage/edit-history': typeof AuthenticatedStorageEditHistoryRoute
  '/storage/report': typeof AuthenticatedStorageReportRoute
  '/transfer/report': typeof AuthenticatedTransferReportRoute
  '/additional': typeof AuthenticatedAdditionalIndexRoute
  '/booking': typeof AuthenticatedBookingIndexRoute
  '/dispatch-pre-storage': typeof AuthenticatedDispatchPreStorageIndexRoute
  '/dispatch': typeof AuthenticatedDispatchIndexRoute
  '/grading': typeof AuthenticatedGradingIndexRoute
  '/incoming': typeof AuthenticatedIncomingIndexRoute
  '/outgoing': typeof AuthenticatedOutgoingIndexRoute
  '/people': typeof AuthenticatedPeopleIndexRoute
  '/storage': typeof AuthenticatedStorageIndexRoute
  '/transfer': typeof AuthenticatedTransferIndexRoute
  '/storage/chamber-breakdown/$chamber': typeof AuthenticatedStorageChamberBreakdownChamberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/daybook': typeof AuthenticatedDaybookRoute
  '/_authenticated/additional/temperature': typeof AuthenticatedAdditionalTemperatureRoute
  '/_authenticated/booking/$id': typeof AuthenticatedBookingIdRoute
  '/_authenticated/booking/edit-history': typeof AuthenticatedBookingEditHistoryRoute
  '/_authenticated/dispatch-post-storage/report': typeof AuthenticatedDispatchPostStorageReportRoute
  '/_authenticated/dispatch-pre-storage/$id': typeof AuthenticatedDispatchPreStorageIdRoute
  '/_authenticated/dispatch-pre-storage/report': typeof AuthenticatedDispatchPreStorageReportRoute
  '/_authenticated/dispatch/$id': typeof AuthenticatedDispatchIdRoute
  '/_authenticated/dispatch/report': typeof AuthenticatedDispatchReportRoute
  '/_authenticated/grading/$id': typeof AuthenticatedGradingIdRoute
  '/_authenticated/grading/edit-history': typeof AuthenticatedGradingEditHistoryRoute
  '/_authenticated/grading/report': typeof AuthenticatedGradingReportRoute
  '/_authenticated/incoming/$id': typeof AuthenticatedIncomingIdRoute
  '/_authenticated/incoming/edit-history': typeof AuthenticatedIncomingEditHistoryRoute
  '/_authenticated/incoming/report': typeof AuthenticatedIncomingReportRoute
  '/_authenticated/people/$id': typeof AuthenticatedPeopleIdRoute
  '/_authenticated/storage/$id': typeof AuthenticatedStorageIdRoute
  '/_authenticated/storage/edit-history': typeof AuthenticatedStorageEditHistoryRoute
  '/_authenticated/storage/report': typeof AuthenticatedStorageReportRoute
  '/_authenticated/transfer/report': typeof AuthenticatedTransferReportRoute
  '/_authenticated/additional/': typeof AuthenticatedAdditionalIndexRoute
  '/_authenticated/booking/': typeof AuthenticatedBookingIndexRoute
  '/_authenticated/dispatch-pre-storage/': typeof AuthenticatedDispatchPreStorageIndexRoute
  '/_authenticated/dispatch/': typeof AuthenticatedDispatchIndexRoute
  '/_authenticated/grading/': typeof AuthenticatedGradingIndexRoute
  '/_authenticated/incoming/': typeof AuthenticatedIncomingIndexRoute
  '/_authenticated/outgoing/': typeof AuthenticatedOutgoingIndexRoute
  '/_authenticated/people/': typeof AuthenticatedPeopleIndexRoute
  '/_authenticated/storage/': typeof AuthenticatedStorageIndexRoute
  '/_authenticated/transfer/': typeof AuthenticatedTransferIndexRoute
  '/_authenticated/storage/chamber-breakdown/$chamber': typeof AuthenticatedStorageChamberBreakdownChamberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/daybook'
    | '/additional/temperature'
    | '/booking/$id'
    | '/booking/edit-history'
    | '/dispatch-post-storage/report'
    | '/dispatch-pre-storage/$id'
    | '/dispatch-pre-storage/report'
    | '/dispatch/$id'
    | '/dispatch/report'
    | '/grading/$id'
    | '/grading/edit-history'
    | '/grading/report'
    | '/incoming/$id'
    | '/incoming/edit-history'
    | '/incoming/report'
    | '/people/$id'
    | '/storage/$id'
    | '/storage/edit-history'
    | '/storage/report'
    | '/transfer/report'
    | '/additional/'
    | '/booking/'
    | '/dispatch-pre-storage/'
    | '/dispatch/'
    | '/grading/'
    | '/incoming/'
    | '/outgoing/'
    | '/people/'
    | '/storage/'
    | '/transfer/'
    | '/storage/chamber-breakdown/$chamber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/daybook'
    | '/additional/temperature'
    | '/booking/$id'
    | '/booking/edit-history'
    | '/dispatch-post-storage/report'
    | '/dispatch-pre-storage/$id'
    | '/dispatch-pre-storage/report'
    | '/dispatch/$id'
    | '/dispatch/report'
    | '/grading/$id'
    | '/grading/edit-history'
    | '/grading/report'
    | '/incoming/$id'
    | '/incoming/edit-history'
    | '/incoming/report'
    | '/people/$id'
    | '/storage/$id'
    | '/storage/edit-history'
    | '/storage/report'
    | '/transfer/report'
    | '/additional'
    | '/booking'
    | '/dispatch-pre-storage'
    | '/dispatch'
    | '/grading'
    | '/incoming'
    | '/outgoing'
    | '/people'
    | '/storage'
    | '/transfer'
    | '/storage/chamber-breakdown/$chamber'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/analytics'
    | '/_authenticated/daybook'
    | '/_authenticated/additional/temperature'
    | '/_authenticated/booking/$id'
    | '/_authenticated/booking/edit-history'
    | '/_authenticated/dispatch-post-storage/report'
    | '/_authenticated/dispatch-pre-storage/$id'
    | '/_authenticated/dispatch-pre-storage/report'
    | '/_authenticated/dispatch/$id'
    | '/_authenticated/dispatch/report'
    | '/_authenticated/grading/$id'
    | '/_authenticated/grading/edit-history'
    | '/_authenticated/grading/report'
    | '/_authenticated/incoming/$id'
    | '/_authenticated/incoming/edit-history'
    | '/_authenticated/incoming/report'
    | '/_authenticated/people/$id'
    | '/_authenticated/storage/$id'
    | '/_authenticated/storage/edit-history'
    | '/_authenticated/storage/report'
    | '/_authenticated/transfer/report'
    | '/_authenticated/additional/'
    | '/_authenticated/booking/'
    | '/_authenticated/dispatch-pre-storage/'
    | '/_authenticated/dispatch/'
    | '/_authenticated/grading/'
    | '/_authenticated/incoming/'
    | '/_authenticated/outgoing/'
    | '/_authenticated/people/'
    | '/_authenticated/storage/'
    | '/_authenticated/transfer/'
    | '/_authenticated/storage/chamber-breakdown/$chamber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daybook': {
      id: '/_authenticated/daybook'
      path: '/daybook'
      fullPath: '/daybook'
      preLoaderRoute: typeof AuthenticatedDaybookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/additional/': {
      id: '/_authenticated/additional/'
      path: '/additional'
      fullPath: '/additional/'
      preLoaderRoute: typeof AuthenticatedAdditionalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/additional/temperature': {
      id: '/_authenticated/additional/temperature'
      path: '/additional/temperature'
      fullPath: '/additional/temperature'
      preLoaderRoute: typeof AuthenticatedAdditionalTemperatureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/booking/': {
      id: '/_authenticated/booking/'
      path: '/booking'
      fullPath: '/booking/'
      preLoaderRoute: typeof AuthenticatedBookingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/booking/$id': {
      id: '/_authenticated/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof AuthenticatedBookingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/booking/edit-history': {
      id: '/_authenticated/booking/edit-history'
      path: '/booking/edit-history'
      fullPath: '/booking/edit-history'
      preLoaderRoute: typeof AuthenticatedBookingEditHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispatch-post-storage/report': {
      id: '/_authenticated/dispatch-post-storage/report'
      path: '/dispatch-post-storage/report'
      fullPath: '/dispatch-post-storage/report'
      preLoaderRoute: typeof AuthenticatedDispatchPostStorageReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispatch-pre-storage/': {
      id: '/_authenticated/dispatch-pre-storage/'
      path: '/dispatch-pre-storage'
      fullPath: '/dispatch-pre-storage/'
      preLoaderRoute: typeof AuthenticatedDispatchPreStorageIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispatch-pre-storage/$id': {
      id: '/_authenticated/dispatch-pre-storage/$id'
      path: '/dispatch-pre-storage/$id'
      fullPath: '/dispatch-pre-storage/$id'
      preLoaderRoute: typeof AuthenticatedDispatchPreStorageIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispatch-pre-storage/report': {
      id: '/_authenticated/dispatch-pre-storage/report'
      path: '/dispatch-pre-storage/report'
      fullPath: '/dispatch-pre-storage/report'
      preLoaderRoute: typeof AuthenticatedDispatchPreStorageReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispatch/': {
      id: '/_authenticated/dispatch/'
      path: '/dispatch'
      fullPath: '/dispatch/'
      preLoaderRoute: typeof AuthenticatedDispatchIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispatch/$id': {
      id: '/_authenticated/dispatch/$id'
      path: '/dispatch/$id'
      fullPath: '/dispatch/$id'
      preLoaderRoute: typeof AuthenticatedDispatchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispatch/report': {
      id: '/_authenticated/dispatch/report'
      path: '/dispatch/report'
      fullPath: '/dispatch/report'
      preLoaderRoute: typeof AuthenticatedDispatchReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grading/': {
      id: '/_authenticated/grading/'
      path: '/grading'
      fullPath: '/grading/'
      preLoaderRoute: typeof AuthenticatedGradingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grading/$id': {
      id: '/_authenticated/grading/$id'
      path: '/grading/$id'
      fullPath: '/grading/$id'
      preLoaderRoute: typeof AuthenticatedGradingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grading/edit-history': {
      id: '/_authenticated/grading/edit-history'
      path: '/grading/edit-history'
      fullPath: '/grading/edit-history'
      preLoaderRoute: typeof AuthenticatedGradingEditHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grading/report': {
      id: '/_authenticated/grading/report'
      path: '/grading/report'
      fullPath: '/grading/report'
      preLoaderRoute: typeof AuthenticatedGradingReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incoming/': {
      id: '/_authenticated/incoming/'
      path: '/incoming'
      fullPath: '/incoming/'
      preLoaderRoute: typeof AuthenticatedIncomingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incoming/$id': {
      id: '/_authenticated/incoming/$id'
      path: '/incoming/$id'
      fullPath: '/incoming/$id'
      preLoaderRoute: typeof AuthenticatedIncomingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incoming/edit-history': {
      id: '/_authenticated/incoming/edit-history'
      path: '/incoming/edit-history'
      fullPath: '/incoming/edit-history'
      preLoaderRoute: typeof AuthenticatedIncomingEditHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incoming/report': {
      id: '/_authenticated/incoming/report'
      path: '/incoming/report'
      fullPath: '/incoming/report'
      preLoaderRoute: typeof AuthenticatedIncomingReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outgoing/': {
      id: '/_authenticated/outgoing/'
      path: '/outgoing'
      fullPath: '/outgoing/'
      preLoaderRoute: typeof AuthenticatedOutgoingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/people/': {
      id: '/_authenticated/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/people/$id': {
      id: '/_authenticated/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof AuthenticatedPeopleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/storage/': {
      id: '/_authenticated/storage/'
      path: '/storage'
      fullPath: '/storage/'
      preLoaderRoute: typeof AuthenticatedStorageIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/storage/$id': {
      id: '/_authenticated/storage/$id'
      path: '/storage/$id'
      fullPath: '/storage/$id'
      preLoaderRoute: typeof AuthenticatedStorageIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/storage/edit-history': {
      id: '/_authenticated/storage/edit-history'
      path: '/storage/edit-history'
      fullPath: '/storage/edit-history'
      preLoaderRoute: typeof AuthenticatedStorageEditHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/storage/report': {
      id: '/_authenticated/storage/report'
      path: '/storage/report'
      fullPath: '/storage/report'
      preLoaderRoute: typeof AuthenticatedStorageReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfer/': {
      id: '/_authenticated/transfer/'
      path: '/transfer'
      fullPath: '/transfer/'
      preLoaderRoute: typeof AuthenticatedTransferIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfer/report': {
      id: '/_authenticated/transfer/report'
      path: '/transfer/report'
      fullPath: '/transfer/report'
      preLoaderRoute: typeof AuthenticatedTransferReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/storage/chamber-breakdown/$chamber': {
      id: '/_authenticated/storage/chamber-breakdown/$chamber'
      path: '/storage/chamber-breakdown/$chamber'
      fullPath: '/storage/chamber-breakdown/$chamber'
      preLoaderRoute: typeof AuthenticatedStorageChamberBreakdownChamberRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDaybookRoute: typeof AuthenticatedDaybookRoute
  AuthenticatedAdditionalTemperatureRoute: typeof AuthenticatedAdditionalTemperatureRoute
  AuthenticatedBookingIdRoute: typeof AuthenticatedBookingIdRoute
  AuthenticatedBookingEditHistoryRoute: typeof AuthenticatedBookingEditHistoryRoute
  AuthenticatedDispatchPostStorageReportRoute: typeof AuthenticatedDispatchPostStorageReportRoute
  AuthenticatedDispatchPreStorageIdRoute: typeof AuthenticatedDispatchPreStorageIdRoute
  AuthenticatedDispatchPreStorageReportRoute: typeof AuthenticatedDispatchPreStorageReportRoute
  AuthenticatedDispatchIdRoute: typeof AuthenticatedDispatchIdRoute
  AuthenticatedDispatchReportRoute: typeof AuthenticatedDispatchReportRoute
  AuthenticatedGradingIdRoute: typeof AuthenticatedGradingIdRoute
  AuthenticatedGradingEditHistoryRoute: typeof AuthenticatedGradingEditHistoryRoute
  AuthenticatedGradingReportRoute: typeof AuthenticatedGradingReportRoute
  AuthenticatedIncomingIdRoute: typeof AuthenticatedIncomingIdRoute
  AuthenticatedIncomingEditHistoryRoute: typeof AuthenticatedIncomingEditHistoryRoute
  AuthenticatedIncomingReportRoute: typeof AuthenticatedIncomingReportRoute
  AuthenticatedPeopleIdRoute: typeof AuthenticatedPeopleIdRoute
  AuthenticatedStorageIdRoute: typeof AuthenticatedStorageIdRoute
  AuthenticatedStorageEditHistoryRoute: typeof AuthenticatedStorageEditHistoryRoute
  AuthenticatedStorageReportRoute: typeof AuthenticatedStorageReportRoute
  AuthenticatedTransferReportRoute: typeof AuthenticatedTransferReportRoute
  AuthenticatedAdditionalIndexRoute: typeof AuthenticatedAdditionalIndexRoute
  AuthenticatedBookingIndexRoute: typeof AuthenticatedBookingIndexRoute
  AuthenticatedDispatchPreStorageIndexRoute: typeof AuthenticatedDispatchPreStorageIndexRoute
  AuthenticatedDispatchIndexRoute: typeof AuthenticatedDispatchIndexRoute
  AuthenticatedGradingIndexRoute: typeof AuthenticatedGradingIndexRoute
  AuthenticatedIncomingIndexRoute: typeof AuthenticatedIncomingIndexRoute
  AuthenticatedOutgoingIndexRoute: typeof AuthenticatedOutgoingIndexRoute
  AuthenticatedPeopleIndexRoute: typeof AuthenticatedPeopleIndexRoute
  AuthenticatedStorageIndexRoute: typeof AuthenticatedStorageIndexRoute
  AuthenticatedTransferIndexRoute: typeof AuthenticatedTransferIndexRoute
  AuthenticatedStorageChamberBreakdownChamberRoute: typeof AuthenticatedStorageChamberBreakdownChamberRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDaybookRoute: AuthenticatedDaybookRoute,
  AuthenticatedAdditionalTemperatureRoute:
    AuthenticatedAdditionalTemperatureRoute,
  AuthenticatedBookingIdRoute: AuthenticatedBookingIdRoute,
  AuthenticatedBookingEditHistoryRoute: AuthenticatedBookingEditHistoryRoute,
  AuthenticatedDispatchPostStorageReportRoute:
    AuthenticatedDispatchPostStorageReportRoute,
  AuthenticatedDispatchPreStorageIdRoute:
    AuthenticatedDispatchPreStorageIdRoute,
  AuthenticatedDispatchPreStorageReportRoute:
    AuthenticatedDispatchPreStorageReportRoute,
  AuthenticatedDispatchIdRoute: AuthenticatedDispatchIdRoute,
  AuthenticatedDispatchReportRoute: AuthenticatedDispatchReportRoute,
  AuthenticatedGradingIdRoute: AuthenticatedGradingIdRoute,
  AuthenticatedGradingEditHistoryRoute: AuthenticatedGradingEditHistoryRoute,
  AuthenticatedGradingReportRoute: AuthenticatedGradingReportRoute,
  AuthenticatedIncomingIdRoute: AuthenticatedIncomingIdRoute,
  AuthenticatedIncomingEditHistoryRoute: AuthenticatedIncomingEditHistoryRoute,
  AuthenticatedIncomingReportRoute: AuthenticatedIncomingReportRoute,
  AuthenticatedPeopleIdRoute: AuthenticatedPeopleIdRoute,
  AuthenticatedStorageIdRoute: AuthenticatedStorageIdRoute,
  AuthenticatedStorageEditHistoryRoute: AuthenticatedStorageEditHistoryRoute,
  AuthenticatedStorageReportRoute: AuthenticatedStorageReportRoute,
  AuthenticatedTransferReportRoute: AuthenticatedTransferReportRoute,
  AuthenticatedAdditionalIndexRoute: AuthenticatedAdditionalIndexRoute,
  AuthenticatedBookingIndexRoute: AuthenticatedBookingIndexRoute,
  AuthenticatedDispatchPreStorageIndexRoute:
    AuthenticatedDispatchPreStorageIndexRoute,
  AuthenticatedDispatchIndexRoute: AuthenticatedDispatchIndexRoute,
  AuthenticatedGradingIndexRoute: AuthenticatedGradingIndexRoute,
  AuthenticatedIncomingIndexRoute: AuthenticatedIncomingIndexRoute,
  AuthenticatedOutgoingIndexRoute: AuthenticatedOutgoingIndexRoute,
  AuthenticatedPeopleIndexRoute: AuthenticatedPeopleIndexRoute,
  AuthenticatedStorageIndexRoute: AuthenticatedStorageIndexRoute,
  AuthenticatedTransferIndexRoute: AuthenticatedTransferIndexRoute,
  AuthenticatedStorageChamberBreakdownChamberRoute:
    AuthenticatedStorageChamberBreakdownChamberRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
