/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedDaybookRouteImport } from './routes/_authenticated/daybook'
import { Route as AuthenticatedPdfReportRouteImport } from './routes/_authenticated/pdf-report'
import { Route as AuthenticatedDispatchPreStorageIndexRouteImport } from './routes/_authenticated/dispatch-pre-storage.index'
import { Route as AuthenticatedDispatchPreStorageIdRouteImport } from './routes/_authenticated/dispatch-pre-storage.$id'
import { Route as AuthenticatedDispatchPreStorageReportRouteImport } from './routes/_authenticated/dispatch-pre-storage.report'
import { Route as AuthenticatedDispatchIndexRouteImport } from './routes/_authenticated/dispatch.index'
import { Route as AuthenticatedDispatchIdRouteImport } from './routes/_authenticated/dispatch.$id'
import { Route as AuthenticatedDispatchReportRouteImport } from './routes/_authenticated/dispatch.report'
import { Route as AuthenticatedFinancesIndexRouteImport } from './routes/_authenticated/finances.index'
import { Route as AuthenticatedLedgersIndexRouteImport } from './routes/_authenticated/ledgers.index'
import { Route as AuthenticatedLedgersIdRouteImport } from './routes/_authenticated/ledgers.$id'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedSettingsBillBooksRouteImport } from './routes/_authenticated/settings.bill-books'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDaybookRoute = AuthenticatedDaybookRouteImport.update({
  id: '/daybook',
  path: '/daybook',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPdfReportRoute = AuthenticatedPdfReportRouteImport.update({
  id: '/pdf-report',
  path: '/pdf-report',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDispatchPreStorageIndexRoute =
  AuthenticatedDispatchPreStorageIndexRouteImport.update({
    id: '/dispatch-pre-storage/',
    path: '/dispatch-pre-storage/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDispatchPreStorageIdRoute =
  AuthenticatedDispatchPreStorageIdRouteImport.update({
    id: '/dispatch-pre-storage/$id',
    path: '/dispatch-pre-storage/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDispatchPreStorageReportRoute =
  AuthenticatedDispatchPreStorageReportRouteImport.update({
    id: '/dispatch-pre-storage/report',
    path: '/dispatch-pre-storage/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDispatchIndexRoute =
  AuthenticatedDispatchIndexRouteImport.update({
    id: '/dispatch/',
    path: '/dispatch/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDispatchIdRoute = AuthenticatedDispatchIdRouteImport.update({
  id: '/dispatch/$id',
  path: '/dispatch/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDispatchReportRoute =
  AuthenticatedDispatchReportRouteImport.update({
    id: '/dispatch/report',
    path: '/dispatch/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesIndexRoute =
  AuthenticatedFinancesIndexRouteImport.update({
    id: '/finances/',
    path: '/finances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLedgersIndexRoute =
  AuthenticatedLedgersIndexRouteImport.update({
    id: '/ledgers/',
    path: '/ledgers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLedgersIdRoute = AuthenticatedLedgersIdRouteImport.update({
  id: '/ledgers/$id',
  path: '/ledgers/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsBillBooksRoute =
  AuthenticatedSettingsBillBooksRouteImport.update({
    id: '/settings/bill-books',
    path: '/settings/bill-books',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daybook': typeof AuthenticatedDaybookRoute
  '/pdf-report': typeof AuthenticatedPdfReportRoute
  '/dispatch-pre-storage/$id': typeof AuthenticatedDispatchPreStorageIdRoute
  '/dispatch-pre-storage/report': typeof AuthenticatedDispatchPreStorageReportRoute
  '/dispatch/$id': typeof AuthenticatedDispatchIdRoute
  '/dispatch/report': typeof AuthenticatedDispatchReportRoute
  '/ledgers/$id': typeof AuthenticatedLedgersIdRoute
  '/settings/bill-books': typeof AuthenticatedSettingsBillBooksRoute
  '/dispatch-pre-storage/': typeof AuthenticatedDispatchPreStorageIndexRoute
  '/dispatch/': typeof AuthenticatedDispatchIndexRoute
  '/finances/': typeof AuthenticatedFinancesIndexRoute
  '/ledgers/': typeof AuthenticatedLedgersIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daybook': typeof AuthenticatedDaybookRoute
  '/pdf-report': typeof AuthenticatedPdfReportRoute
  '/dispatch-pre-storage/$id': typeof AuthenticatedDispatchPreStorageIdRoute
  '/dispatch-pre-storage/report': typeof AuthenticatedDispatchPreStorageReportRoute
  '/dispatch/$id': typeof AuthenticatedDispatchIdRoute
  '/dispatch/report': typeof AuthenticatedDispatchReportRoute
  '/ledgers/$id': typeof AuthenticatedLedgersIdRoute
  '/settings/bill-books': typeof AuthenticatedSettingsBillBooksRoute
  '/dispatch-pre-storage': typeof AuthenticatedDispatchPreStorageIndexRoute
  '/dispatch': typeof AuthenticatedDispatchIndexRoute
  '/finances': typeof AuthenticatedFinancesIndexRoute
  '/ledgers': typeof AuthenticatedLedgersIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/daybook': typeof AuthenticatedDaybookRoute
  '/_authenticated/pdf-report': typeof AuthenticatedPdfReportRoute
  '/_authenticated/dispatch-pre-storage/$id': typeof AuthenticatedDispatchPreStorageIdRoute
  '/_authenticated/dispatch-pre-storage/report': typeof AuthenticatedDispatchPreStorageReportRoute
  '/_authenticated/dispatch/$id': typeof AuthenticatedDispatchIdRoute
  '/_authenticated/dispatch/report': typeof AuthenticatedDispatchReportRoute
  '/_authenticated/ledgers/$id': typeof AuthenticatedLedgersIdRoute
  '/_authenticated/settings/bill-books': typeof AuthenticatedSettingsBillBooksRoute
  '/_authenticated/dispatch-pre-storage/': typeof AuthenticatedDispatchPreStorageIndexRoute
  '/_authenticated/dispatch/': typeof AuthenticatedDispatchIndexRoute
  '/_authenticated/finances/': typeof AuthenticatedFinancesIndexRoute
  '/_authenticated/ledgers/': typeof AuthenticatedLedgersIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daybook'
    | '/pdf-report'
    | '/dispatch-pre-storage/$id'
    | '/dispatch-pre-storage/report'
    | '/dispatch/$id'
    | '/dispatch/report'
    | '/ledgers/$id'
    | '/settings/bill-books'
    | '/dispatch-pre-storage/'
    | '/dispatch/'
    | '/finances/'
    | '/ledgers/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daybook'
    | '/pdf-report'
    | '/dispatch-pre-storage/$id'
    | '/dispatch-pre-storage/report'
    | '/dispatch/$id'
    | '/dispatch/report'
    | '/ledgers/$id'
    | '/settings/bill-books'
    | '/dispatch-pre-storage'
    | '/dispatch'
    | '/finances'
    | '/ledgers'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/daybook'
    | '/_authenticated/pdf-report'
    | '/_authenticated/dispatch-pre-storage/$id'
    | '/_authenticated/dispatch-pre-storage/report'
    | '/_authenticated/dispatch/$id'
    | '/_authenticated/dispatch/report'
    | '/_authenticated/ledgers/$id'
    | '/_authenticated/settings/bill-books'
    | '/_authenticated/dispatch-pre-storage/'
    | '/_authenticated/dispatch/'
    | '/_authenticated/finances/'
    | '/_authenticated/ledgers/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/daybook': {
      id: '/_authenticated/daybook'
      path: '/daybook'
      fullPath: '/daybook'
      preLoaderRoute: typeof AuthenticatedDaybookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pdf-report': {
      id: '/_authenticated/pdf-report'
      path: '/pdf-report'
      fullPath: '/pdf-report'
      preLoaderRoute: typeof AuthenticatedPdfReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispatch-pre-storage/': {
      id: '/_authenticated/dispatch-pre-storage/'
      path: '/dispatch-pre-storage'
      fullPath: '/dispatch-pre-storage/'
      preLoaderRoute: typeof AuthenticatedDispatchPreStorageIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispatch-pre-storage/$id': {
      id: '/_authenticated/dispatch-pre-storage/$id'
      path: '/dispatch-pre-storage/$id'
      fullPath: '/dispatch-pre-storage/$id'
      preLoaderRoute: typeof AuthenticatedDispatchPreStorageIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispatch-pre-storage/report': {
      id: '/_authenticated/dispatch-pre-storage/report'
      path: '/dispatch-pre-storage/report'
      fullPath: '/dispatch-pre-storage/report'
      preLoaderRoute: typeof AuthenticatedDispatchPreStorageReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispatch/': {
      id: '/_authenticated/dispatch/'
      path: '/dispatch'
      fullPath: '/dispatch/'
      preLoaderRoute: typeof AuthenticatedDispatchIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispatch/$id': {
      id: '/_authenticated/dispatch/$id'
      path: '/dispatch/$id'
      fullPath: '/dispatch/$id'
      preLoaderRoute: typeof AuthenticatedDispatchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispatch/report': {
      id: '/_authenticated/dispatch/report'
      path: '/dispatch/report'
      fullPath: '/dispatch/report'
      preLoaderRoute: typeof AuthenticatedDispatchReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/': {
      id: '/_authenticated/finances/'
      path: '/finances'
      fullPath: '/finances/'
      preLoaderRoute: typeof AuthenticatedFinancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ledgers/': {
      id: '/_authenticated/ledgers/'
      path: '/ledgers'
      fullPath: '/ledgers/'
      preLoaderRoute: typeof AuthenticatedLedgersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ledgers/$id': {
      id: '/_authenticated/ledgers/$id'
      path: '/ledgers/$id'
      fullPath: '/ledgers/$id'
      preLoaderRoute: typeof AuthenticatedLedgersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/bill-books': {
      id: '/_authenticated/settings/bill-books'
      path: '/settings/bill-books'
      fullPath: '/settings/bill-books'
      preLoaderRoute: typeof AuthenticatedSettingsBillBooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDaybookRoute: typeof AuthenticatedDaybookRoute
  AuthenticatedPdfReportRoute: typeof AuthenticatedPdfReportRoute
  AuthenticatedDispatchPreStorageIdRoute: typeof AuthenticatedDispatchPreStorageIdRoute
  AuthenticatedDispatchPreStorageReportRoute: typeof AuthenticatedDispatchPreStorageReportRoute
  AuthenticatedDispatchIdRoute: typeof AuthenticatedDispatchIdRoute
  AuthenticatedDispatchReportRoute: typeof AuthenticatedDispatchReportRoute
  AuthenticatedLedgersIdRoute: typeof AuthenticatedLedgersIdRoute
  AuthenticatedSettingsBillBooksRoute: typeof AuthenticatedSettingsBillBooksRoute
  AuthenticatedDispatchPreStorageIndexRoute: typeof AuthenticatedDispatchPreStorageIndexRoute
  AuthenticatedDispatchIndexRoute: typeof AuthenticatedDispatchIndexRoute
  AuthenticatedFinancesIndexRoute: typeof AuthenticatedFinancesIndexRoute
  AuthenticatedLedgersIndexRoute: typeof AuthenticatedLedgersIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDaybookRoute: AuthenticatedDaybookRoute,
  AuthenticatedPdfReportRoute: AuthenticatedPdfReportRoute,
  AuthenticatedDispatchPreStorageIdRoute:
    AuthenticatedDispatchPreStorageIdRoute,
  AuthenticatedDispatchPreStorageReportRoute:
    AuthenticatedDispatchPreStorageReportRoute,
  AuthenticatedDispatchIdRoute: AuthenticatedDispatchIdRoute,
  AuthenticatedDispatchReportRoute: AuthenticatedDispatchReportRoute,
  AuthenticatedLedgersIdRoute: AuthenticatedLedgersIdRoute,
  AuthenticatedSettingsBillBooksRoute: AuthenticatedSettingsBillBooksRoute,
  AuthenticatedDispatchPreStorageIndexRoute:
    AuthenticatedDispatchPreStorageIndexRoute,
  AuthenticatedDispatchIndexRoute: AuthenticatedDispatchIndexRoute,
  AuthenticatedFinancesIndexRoute: AuthenticatedFinancesIndexRoute,
  AuthenticatedLedgersIndexRoute: AuthenticatedLedgersIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
